%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\schroemz\OneDrive - University of Birmingham\Documents\GitHub\Sickness-and-the-City\Data\Glasgow_Resp_Diseases.xlsx
%    Worksheet: Data
%
% Auto-generated by MATLAB on 23-Apr-2023 12:27:21

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 7);

% Specify sheet and range
opts.Sheet = "Data";
opts.DataRange = "A2:G76";

% Specify column names and types
opts.VariableNames = ["Year", "Pneumonia", "Bronchitis", "Influenza", "Selected_Resp", "Whooping_Cough", "Pulmonary_Tuberculosis"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double"];

% Import the data
Glasgow_Data = readtable("..\Data\Glasgow_Resp_Diseases.xlsx", opts, "UseExcel", false);


%% Clear temporary variables
clear opts

%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\schroemz\OneDrive - University of Birmingham\Documents\GitHub\Sickness-and-the-City\Data\EnglandWales_Data.xls
%    Worksheet: England & Wales
%
% Auto-generated by MATLAB on 23-Apr-2023 12:28:27

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 2);

% Specify sheet and range
opts.Sheet = "England & Wales";
opts.DataRange = "A2:B76";

% Specify column names and types
opts.VariableNames = ["Year", "InfluenzaMortalityRate"];
opts.VariableTypes = ["double", "double"];

% Import the data
EnglandWales_Data = readtable("..\Data\EnglandWales_Data.xls", opts, "UseExcel", false);


%% Clear temporary variables
clear opts

%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: D:\Documents\GitHub\Sickness-and-the-City\Data\MSwitchingModel.xls
%    Worksheet: Glasgow Influenza
%
% Auto-generated by MATLAB on 27-Apr-2023 16:59:43

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 3);

% Specify sheet and range
opts.Sheet = "Glasgow Influenza";
opts.DataRange = "A2:C76";

% Specify column names and types
opts.VariableNames = ["Year", "log_influenza", "prob"];
opts.VariableTypes = ["double", "double", "double"];

% Import the data
MSM_Glasgow_Influenza = readtable("..\Outputs\MSwitchingModel.xls", opts, "UseExcel", false);

